services:
  docflow-360-monorepo:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_VERSION: "24.14.0"
    command: ["pnpm","--filter","docflow-360-monorepo","dev"]
    restart: unless-stopped
    environment:
      NODE_ENV: production
  docflow-360-ai-runtime:
    build:
      context: .
      dockerfile: apps/ai-runtime/Dockerfile
      args:
        NODE_VERSION: "24.14.0"
    command: ["pnpm","--filter","docflow-360-ai-runtime","start"]
    restart: unless-stopped
    environment:
      NODE_ENV: production
  docflow-360-core-api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
      args:
        NODE_VERSION: "24.14.0"
    command: ["pnpm","--filter","docflow-360-core-api","start"]
    restart: unless-stopped
    environment:
      NODE_ENV: production
  docflow-360-scheduler:
    build:
      context: .
      dockerfile: apps/scheduler/Dockerfile
      args:
        NODE_VERSION: "24.14.0"
    command: ["pnpm","--filter","docflow-360-scheduler","start"]
    restart: unless-stopped
    environment:
      NODE_ENV: production
  docflow-360-frontend:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        NODE_VERSION: "24.14.0"
    command: ["pnpm","--filter","docflow-360-frontend","start"]
    restart: unless-stopped
    environment:
      NODE_ENV: production
  docflow-360-worker:
    build:
      context: .
      dockerfile: apps/worker/Dockerfile
      args:
        NODE_VERSION: "24.14.0"
    command: ["pnpm","--filter","docflow-360-worker","start"]
    restart: unless-stopped
    environment:
      NODE_ENV: production
