export enum Cities {
    // Major cities across all states
    NEW_YORK = 'New York',
    LOS_ANGELES = 'Los Angeles',
    CHICAGO = 'Chicago',
    HOUSTON = 'Houston',
    PHOENIX = 'Phoenix',
    PHILADELPHIA = 'Philadelphia',
    SAN_ANTONIO = 'San Antonio',
    SAN_DIEGO = 'San Diego',
    DALLAS = 'Dallas',
    SAN_JOSE = 'San Jose',
    AUSTIN = 'Austin',
    JACKSONVILLE = 'Jacksonville',
    FORT_WORTH = 'Fort Worth',
    COLUMBUS = 'Columbus',
    CHARLOTTE = 'Charlotte',
    SAN_FRANCISCO = 'San Francisco',
    INDIANAPOLIS = 'Indianapolis',
    SEATTLE = 'Seattle',
    DENVER = 'Denver',
    WASHINGTON = 'Washington',
    BOSTON = 'Boston',
    EL_PASO = 'El Paso',
    NASHVILLE = 'Nashville',
    DETROIT = 'Detroit',
    OKLAHOMA_CITY = 'Oklahoma City',
    PORTLAND = 'Portland',
    LAS_VEGAS = 'Las Vegas',
    MEMPHIS = 'Memphis',
    LOUISVILLE = 'Louisville',
    BALTIMORE = 'Baltimore',
    MILWAUKEE = 'Milwaukee',
    ALBUQUERQUE = 'Albuquerque',
    TUCSON = 'Tucson',
    FRESNO = 'Fresno',
    MESA = 'Mesa',
    SACRAMENTO = 'Sacramento',
    ATLANTA = 'Atlanta',
    KANSAS_CITY = 'Kansas City',
    COLORADO_SPRINGS = 'Colorado Springs',
    RALEIGH = 'Raleigh',
    OMAHA = 'Omaha',
    MIAMI = 'Miami',
    LONG_BEACH = 'Long Beach',
    VIRGINIA_BEACH = 'Virginia Beach',
    OAKLAND = 'Oakland',
    MINNEAPOLIS = 'Minneapolis',
    TULSA = 'Tulsa',
    TAMPA = 'Tampa',
    ARLINGTON = 'Arlington',
    NEW_ORLEANS = 'New Orleans',
    WICHITA = 'Wichita',
    CLEVELAND = 'Cleveland',
    BAKERSFIELD = 'Bakersfield',
    AURORA = 'Aurora',
    ANAHEIM = 'Anaheim',
    HONOLULU = 'Honolulu',
    SANTA_ANA = 'Santa Ana',
    RIVERSIDE = 'Riverside',
    CORPUS_CHRISTI = 'Corpus Christi',
    LEXINGTON = 'Lexington',
    HENDERSON = 'Henderson',
    STOCKTON = 'Stockton',
    SAINT_PAUL = 'Saint Paul',
    CINCINNATI = 'Cincinnati',
    ST_LOUIS = 'St. Louis',
    PITTSBURGH = 'Pittsburgh',
    GREENSBORO = 'Greensboro',
    LINCOLN = 'Lincoln',
    ANCHORAGE = 'Anchorage',
    PLANO = 'Plano',
    ORLANDO = 'Orlando',
    IRVINE = 'Irvine',
    NEWARK = 'Newark',
    DURHAM = 'Durham',
    CHULA_VISTA = 'Chula Vista',
    TOLEDO = 'Toledo',
    FORT_WAYNE = 'Fort Wayne',
    ST_PETERSBURG = 'St. Petersburg',
    LAREDO = 'Laredo',
    JERSEY_CITY = 'Jersey City',
    CHANDLER = 'Chandler',
    MADISON = 'Madison',
    LUBBOCK = 'Lubbock',
    SCOTTSDALE = 'Scottsdale',
    RENO = 'Reno',
    BUFFALO = 'Buffalo',
    GILBERT = 'Gilbert',
    GLENDALE = 'Glendale',
    NORTH_LAS_VEGAS = 'North Las Vegas',
    WINSTON_SALEM = 'Winston-Salem',
    CHESAPEAKE = 'Chesapeake',
    NORFOLK = 'Norfolk',
    FREMONT = 'Fremont',
    GARLAND = 'Garland',
    IRVING = 'Irving',
    HIALEAH = 'Hialeah',
    RICHMOND = 'Richmond',
    BOISE = 'Boise',
    SPOKANE = 'Spokane',
    BATON_ROUGE = 'Baton Rouge',
}

export enum States {
    AL = 'AL', // Alabama
    AK = 'AK', // Alaska
    AZ = 'AZ', // Arizona
    AR = 'AR', // Arkansas
    CA = 'CA', // California
    CO = 'CO', // Colorado
    CT = 'CT', // Connecticut
    DE = 'DE', // Delaware
    FL = 'FL', // Florida
    GA = 'GA', // Georgia
    HI = 'HI', // Hawaii
    ID = 'ID', // Idaho
    IL = 'IL', // Illinois
    IN = 'IN', // Indiana
    IA = 'IA', // Iowa
    KS = 'KS', // Kansas
    KY = 'KY', // Kentucky
    LA = 'LA', // Louisiana
    ME = 'ME', // Maine
    MD = 'MD', // Maryland
    MA = 'MA', // Massachusetts
    MI = 'MI', // Michigan
    MN = 'MN', // Minnesota
    MS = 'MS', // Mississippi
    MO = 'MO', // Missouri
    MT = 'MT', // Montana
    NE = 'NE', // Nebraska
    NV = 'NV', // Nevada
    NH = 'NH', // New Hampshire
    NJ = 'NJ', // New Jersey
    NM = 'NM', // New Mexico
    NY = 'NY', // New York
    NC = 'NC', // North Carolina
    ND = 'ND', // North Dakota
    OH = 'OH', // Ohio
    OK = 'OK', // Oklahoma
    OR = 'OR', // Oregon
    PA = 'PA', // Pennsylvania
    RI = 'RI', // Rhode Island
    SC = 'SC', // South Carolina
    SD = 'SD', // South Dakota
    TN = 'TN', // Tennessee
    TX = 'TX', // Texas
    UT = 'UT', // Utah
    VT = 'VT', // Vermont
    VA = 'VA', // Virginia
    WA = 'WA', // Washington
    WV = 'WV', // West Virginia
    WI = 'WI', // Wisconsin
    WY = 'WY', // Wyoming
}
